version: '3.8'

services:
  project-management-db:
    image: postgres:13
    container_name: project-management-db
    environment:
      POSTGRES_DB: project_management_db
      POSTGRES_USER: projectuser
      POSTGRES_PASSWORD: projectpassword
    volumes:
      - project-management-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - project-management-network

  project-management-service:
    image: project-management-service:latest
    container_name: project-management-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://project-postgres-service:5432/project-service
      SPRING_DATASOURCE_USERNAME: projectuser
      SPRING_DATASOURCE_PASSWORD: projectpassword
    ports:
      - "3003:3003"
    depends_on:
      - project-management-db
    networks:
      - project-management-network

networks:
  project-management-network:
    driver: bridge

volumes:
  project-management-db-data:
