version: '3.8'
services:
  auth-service:
    build: ../services/auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
  user-management-service:
    build: ../services/user-management-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
  project-management-service:
    build: ../services/project-management-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
  search-filter-service:
    build: ../services/search-filter-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
