apiVersion: v1
kind: Service
metadata:
  name: project-postgres-service
spec:
  ports:
    - port: 5432
  selector:
    app: project-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-postgres
  template:
    metadata:
      labels:
        app: project-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "project-service"
        - name: POSTGRES_USER
          value: "projectuser"
        - name: POSTGRES_PASSWORD
          value: "projectpassword"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
      - name: postgres-storage
        emptyDir: {}
